### ISSUE TITLE
`Sledge Hammer` mod: `NoClassDefFoundError: io/github/lxgaming/sledgehammer/mixin/forge/fml/common/FMLModContainerAccessor`

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/Fugue#16]
[crash-2024-02-11_12.02.38-client.txt](https://github.com/CleanroomMC/Fugue/files/14231826/crash-2024-02-11_12.02.38-client.txt)

**Comment by Krutoy242** [comment]
I made a test - i set Sledge Hammer config for everything `=false` except this config:
```less
    # BiblioCraft
    bibliocraft {
        # If 'true', fixes AbstractMethodError caused by missing getStackInSlot method
        abstract-stack-in-slot=true
    }
```

This resulted in crash:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BiblioCraft (bibliocraft)
Caused by: java.lang.NoClassDefFoundError: jds/bibliocraft/tileentities/TileEntityFramedChest
    at jds.bibliocraft.BiblioCraft.preInitClient(BiblioCraft.java:192)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jds.bibliocraft.tileentities.TileEntityFramedChest
Caused by: java.lang.NoClassDefFoundError: jds/bibliocraft/tileentities/BiblioTileEntity
Caused by: java.lang.ClassNotFoundException: jds.bibliocraft.tileentities.BiblioTileEntity
```

**Comment by ZZZank** [comment]
> This resulted in crash:
> ```
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BiblioCraft (bibliocraft)
> Caused by: java.lang.NoClassDefFoundError: jds/bibliocraft/tileentities/TileEntityFramedChest
>     at jds.bibliocraft.BiblioCraft.preInitClient(BiblioCraft.java:192)
>     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
> Caused by: java.lang.ClassNotFoundException: jds.bibliocraft.tileentities.TileEntityFramedChest
> Caused by: java.lang.NoClassDefFoundError: jds/bibliocraft/tileentities/BiblioTileEntity
> Caused by: java.lang.ClassNotFoundException: jds.bibliocraft.tileentities.BiblioTileEntity
> ```

I think the part displayed here might not be complete enough - `jds/bibliocraft/tileentities/TileEntityFramedChest` is abosolutely defined, as there's [source code for it](https://github.com/Nuchaz/BiblioCraft-Source/blob/1.12.2/src/main/java/jds/bibliocraft/tileentities/TileEntityFramedChest.java). 

According to my experience, when such error happened, you can scroll back a bit in `latest.log` , and it's very likely to locate a line saying `some-mod failing to modify some-class` (I dont remember what exactly its format is). 

And here, that `some-class` should be exactly `jds/bibliocraft/tileentities/TileEntityFramedChest` ,or `jds.bibliocraft.tileentities.TileEntityFramedChest`, while `some-mod` should be Sledge Hammer

**Comment by kappa-maintainer** [comment]
Should have fixed in exp fugue
