### ISSUE TITLE
`0.5.4` => `0.9.4` update crash: `NoClassDefFoundError: top/outlands/foundation/IExplicitTransformer`

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/Fugue#24]
This is probably means, that my modpack `E2E-E` doesn't have `Outlands` installed.

```ruby
[main/FATAL] [Bouncepad]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at E:\mc\packs\E2EE Java 21\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:118) ~[cleanroom-15.24.0.3029-universal.jar:?]
[...]
Caused by: java.lang.NoClassDefFoundError: top/outlands/foundation/IExplicitTransformer
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
[...]
Caused by: java.lang.ClassNotFoundException: top.outlands.foundation.IExplicitTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:230) ~[bouncepad-0.4.35-cursed.jar:?]
[...]
Caused by: java.lang.NullPointerException: Cannot read the array length because "transformedClass" is null
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:219) ~[bouncepad-0.4.35-cursed.jar:?]
```

[debug-2.log.gz](https://github.com/CleanroomMC/Fugue/files/14597799/debug-2.log.gz)

**Comment by kappa-maintainer** [comment]
Please use latest CleanroomMMC pack

**Comment by Krutoy242** [comment]
> CleanroomMMC pack

What is CleanroomMMC pack? Does this means i need to update both CMMC and Fugue?

**Comment by kappa-maintainer** [comment]
https://github.com/CleanroomMC/CleanroomMMC/actions/
I recommend you joining our Discord server to track latest changes
