### ISSUE TITLE
Fugue seems unable to modify final fields from Dropt

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/Fugue#26]
[latest.log](https://github.com/CleanroomMC/Fugue/files/14624193/latest.log)
[crash-2024-03-16_23.26.18-client.txt](https://github.com/CleanroomMC/Fugue/files/14624195/crash-2024-03-16_23.26.18-client.txt)
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dropt (dropt)
Caused by: java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: com.codetaylor.mc.dropt.api.DroptAPI.SUPPLIER_MOD_ID/java.util.function.Supplier/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:167)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:145)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1200)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1169)
	at java.base/java.lang.reflect.Field.set(Field.java:836)
	at com.codetaylor.mc.athenaeum.util.Injector.inject(Injector.java:18)
...
```
I tried adding `S:com.codetaylor.mc.dropt.api.DroptAPI=SUPPLIER_MOD_ID` in `finalremovingtargets`, but the crash report looks exactly the same, so i'm only uploading one crash report. 

## reproducing
I can reporduce this using and only using:
- loader: Cleanroom 15.24.0.3032 (https://github.com/CleanroomMC/Cleanroom/actions/runs/8294172266)
- mod: Fugue-0.10.1
- mod: dropt-1.12.2-1.19.3.jar
- mod: athenaeum-1.12.2-1.19.6.jar

It will crash on game start.

## additional info
The `SUPPLIER_MOD_ID` is not initalized using conventional route: 
https://github.com/codetaylor/dropt-1.12/blob/21cf4014342ec5b856de2021ed703a75da30a595/src/api/java/com/codetaylor/mc/dropt/api/DroptAPI.java#L16-L24
```
  private static final Supplier<String> SUPPLIER_MOD_ID = null;
```

It's actually injected on FMLConstructionEvent, see: 
https://github.com/codetaylor/dropt-1.12/blob/21cf4014342ec5b856de2021ed703a75da30a595/src/main/java/com/codetaylor/mc/dropt/modules/dropt/ModuleDropt.java#L112

And the injector it used is: 
https://github.com/codetaylor/athenaeum-1.12/blob/master/src/main/java/com/codetaylor/mc/athenaeum/util/Injector.java

That's all I can find.

**Comment by kappa-maintainer** [comment]
In this case, just add `com.codetaylor.mc.athenaeum.util.Injector` to Field.set() target instead
Final field stripper is mainly for Mixin without @ Mutable

**Comment by ZZZank** [comment]
> In this case, just add `com.codetaylor.mc.athenaeum.util.Injector` to Field.set() target instead

Got it, and it does works, thanks!
