### ISSUE TITLE
CraftTweaker的.zs脚本在加载世界时脚错 Method must be InterfaceMethodref constant

### ISSUE THREAD

**Issue by abmcar** [CleanroomMC/Fugue#29]
```
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [preinit]: Error executing {[0:preinit]: Textures.zs}: Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChangeError: Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [gregtech]: Error executing {[10:gregtech]: oreprefix.zs}: Method 'com.zook.devtech.api.unification.material.IMaterialFlagBuilder com.zook.devtech.api.unification.material.IMaterialFlagBuilder.create(java.lang.String)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChangeError: Method 'com.zook.devtech.api.unification.material.IMaterialFlagBuilder com.zook.devtech.api.unification.material.IMaterialFlagBuilder.create(java.lang.String)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectEmerald>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectDiamond>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: Midgame.zs}: Method 'void com.zook.devtech.api.unification.ore.IOrePrefix.generateRecipes(gregtech.api.unification.ore.OrePrefix, com.zook.devtech.api.unification.ore.IOreRecipeHandler)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChangeError: Method 'void com.zook.devtech.api.unification.ore.IOrePrefix.generateRecipes(gregtech.api.unification.ore.OrePrefix, com.zook.devtech.api.unification.ore.IOreRecipeHandler)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectDiamond>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: multiblocks_normal.zs}: stack cannot be null, caused by java.lang.IllegalArgumentException: stack cannot be null
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [preinit]: Error executing {[0:preinit]: Textures.zs}: Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChangeError: Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [gregtech]: Error executing {[10:gregtech]: oreprefix.zs}: Method 'com.zook.devtech.api.unification.material.IMaterialFlagBuilder com.zook.devtech.api.unification.material.IMaterialFlagBuilder.create(java.lang.String)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChangeError: Method 'com.zook.devtech.api.unification.material.IMaterialFlagBuilder com.zook.devtech.api.unification.material.IMaterialFlagBuilder.create(java.lang.String)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectEmerald>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectDiamond>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: Midgame.zs}: Method 'void com.zook.devtech.api.unification.ore.IOrePrefix.generateRecipes(gregtech.api.unification.ore.OrePrefix, com.zook.devtech.api.unification.ore.IOreRecipeHandler)' must be InterfaceMethodref constant, caused by java.lang.IncompatibleClassChaongeError: Method 'void com.zook.devtech.api.unification.ore.IOrePrefix.generateRecipes(gregtech.api.unification.ore.OrePrefix, com.zook.devtech.api.unification.ore.IOreRecipeHandler)' must be InterfaceMethodref constant
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: Could not resolve <metaitem:devtech:gemPerfectDiamond>
[19:19:13] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] §cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: multiblocks_normal.zs}: stack cannot be null, caused by java.lang.IllegalArgumentException: stack cannot be null
```
省流版
```
[preinit]: Error executing {[0:preinit]: Textures.zs}: 
Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant, 
caused by java.lang.IncompatibleClassChangeError: 
Method 'eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea eutros.multiblocktweaker.crafttweaker.gtwrap.interfaces.ITextureArea.fullImage(java.lang.String)' must be InterfaceMethodref constant

```
所使用整合包为Nomifactory
第一个报错的Textures.zs如下
```
#loader preinit

import mods.gregtech.render.ITextureArea;

val rocket_arrow as ITextureArea = ITextureArea.fullImage("multiblocktweaker:textures/gui/progress_bar/rocket.png");
```
第二个报错的oreprefix.zs如下 其他报错的内容就不放了，有需要再放
```
#loader gregtech
#priority 10

import mods.gregtech.material.MaterialBuilder;
import mods.gregtech.material.MaterialRegistry;
import mods.gregtech.material.IMaterialPredicate;
import mods.gregtech.material.Material;
import mods.gregtech.material.Elements;
import mods.gregtech.ore.OrePrefix;
import mods.gregtech.recipe.helpers;
import mods.gregtech.ore.IOreRecipeHandler;
import mods.gregtech.MaterialFlag;
import mods.gregtech.recipe.RecipeMap;
import mods.gregtech.MaterialFlagBuilder;

val gemPerfectFlag = MaterialFlagBuilder.create("generate_perfect")
    .requireGem()
    .build();

<material:diamond>.addFlags(["generate_perfect"]);
<material:emerald>.addFlags(["generate_perfect"]);
<material:ruby>.addFlags(["generate_perfect"]);
<material:topaz>.addFlags(["generate_perfect"]);

val gemPerfect as OrePrefix = OrePrefix.registerOrePrefix("gemPerfect", 8, "gemPerfect", 1);
gemPerfect.setGenerationPredicate(function(mat as Material) as bool {
    return mat.hasFlag(gemPerfectFlag);
} as IMaterialPredicate);

gemPerfect.createMaterialItem();
```

不知道 #19 是不是跟这个一个问题

**Comment by kappa-maintainer** [comment]
先试下更新CrT到最新，这个问题我记得官方修过一次

**Comment by abmcar** [comment]
确实可以了，另外报一个ae在退出存档时会崩溃的问题
把appeng.me.GridStorage放到remapTargets可以解决，望在下个版本放到默认配置里
除此之外玩nomifactory没什么问题了，感谢大佬贡献，爱你 啵啵
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AE2 Unofficial Extended Life (appliedenergistics2)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
    at appeng.me.GridStorage.getValue(GridStorage.java:98)
    at appeng.core.worlddata.StorageData.onWorldStop(StorageData.java:139)
    at appeng.core.worlddata.WorldData.onServerStopping(WorldData.java:155)
    at appeng.core.AppEng.serverStopping(AppEng.java:238)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
    at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
    at com.google.common.eventbus.EventBus.post(EventBus.java:270)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:279)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:257)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
    at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
    at com.google.common.eventbus.EventBus.post(EventBus.java:270)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:193)
    at net.minecraftforge.fml.common.Loader.serverStopping(Loader.java:811)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:308)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533)
    at java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
    ... 32 more
```
