### ISSUE TITLE
Fugue 0.13.0 crash: `ClassNotFoundException: top.outlands.foundation.IExplicitTransformer`

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/Fugue#33]
I just updated Fugue from 0.5.4 version. Cant load MC - as fast as i start to load it i got this crash:

```
[main/FATAL] [Bouncepad]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at E:\mc\packs\E2EE Java 21\.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:118) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:85) ~[cleanroom-15.24.0.3029-universal.jar:?]
	[...]
Caused by: java.lang.NoClassDefFoundError: top/outlands/foundation/IExplicitTransformer
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	[...]
Caused by: java.lang.ClassNotFoundException: top.outlands.foundation.IExplicitTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:230) ~[bouncepad-0.4.40-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	[...]
Caused by: java.lang.NullPointerException: Cannot read the array length because "transformedClass" is null
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:219) ~[bouncepad-0.4.40-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	[...]
```

### https://mclo.gs/K9M6gTe

**Comment by kappa-maintainer** [comment]
0.9.+ is for exp branch, remember?
Next time ask in Discord first
