### ISSUE TITLE
Any version above 0.5.4 crashes at startup.

### ISSUE THREAD

**Issue by mattys1** [CleanroomMC/Fugue#36]
Using this build of Cleanroom for most of my testing: `https://github.com/CleanroomMC/CleanroomMMC/actions/runs/8564129681`, though I've also done testing on an older version (albeit that instance had other mods installed) and it's crashing with the same error message.

No matter what version of Fugue I'm using, if it's newer than 0.5.4 (I've not tested older versions), the game crashes at startup with the same error message.

Here's the log, using Fugue 0.14.0:

```
PollyMC version: 8.0 (official)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.44, 13.107.246.44, 2620:1ec:46::44, 2620:1ec:bdf::44]

textures.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44, 2620:1ec:bdf::44, 2620:1ec:46::44]

api.mojang.com resolves to:
    [13.107.246.44, 13.107.213.44, 2620:1ec:bdf::44, 2620:1ec:46::44]


Minecraft folder is:
/mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/.minecraft


Java path is:
/mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/Java/graalvm-jdk-21.0.2+13.1/bin/java


Java is version 21.0.2, using 64 (amd64) architecture, from Oracle Corporation.


AMD Ryzen 5 7600 6-Core Processor
NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

Subsystem: ZOTAC International (MCO) Ltd. Device 1438

Kernel driver in use: nvidia

Advanced Micro Devices, Inc. [AMD/ATI] Raphael (rev c6)

Subsystem: Micro-Star International Co., Ltd. [MSI] Device 7d78

Kernel driver in use: amdgpu

OpenGL version string: 4.6.0 NVIDIA 550.67

Main Class:
  com.cleanroommc.bouncepad.Bouncepad

Native path:
  /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-glfw/3.3.4-27-CLEANROOM/lwjgl3-glfw-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-jemalloc/3.3.4-27-CLEANROOM/lwjgl3-jemalloc-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-openal/3.3.4-27-CLEANROOM/lwjgl3-openal-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-opengl/3.3.4-27-CLEANROOM/lwjgl3-opengl-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-stb/3.3.4-27-CLEANROOM/lwjgl3-stb-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-tinyfd/3.3.4-27-CLEANROOM/lwjgl3-tinyfd-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3/3.3.4-27-CLEANROOM/lwjgl3-3.3.4-27-CLEANROOM.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-glfw/3.3.4-27-CLEANROOM/lwjgl3-glfw-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-glfw/3.3.4-27-CLEANROOM/lwjgl3-glfw-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-glfw/3.3.4-27-CLEANROOM/lwjgl3-glfw-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-jemalloc/3.3.4-27-CLEANROOM/lwjgl3-jemalloc-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-jemalloc/3.3.4-27-CLEANROOM/lwjgl3-jemalloc-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-jemalloc/3.3.4-27-CLEANROOM/lwjgl3-jemalloc-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-openal/3.3.4-27-CLEANROOM/lwjgl3-openal-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-openal/3.3.4-27-CLEANROOM/lwjgl3-openal-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-openal/3.3.4-27-CLEANROOM/lwjgl3-openal-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-opengl/3.3.4-27-CLEANROOM/lwjgl3-opengl-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-opengl/3.3.4-27-CLEANROOM/lwjgl3-opengl-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-opengl/3.3.4-27-CLEANROOM/lwjgl3-opengl-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-stb/3.3.4-27-CLEANROOM/lwjgl3-stb-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-stb/3.3.4-27-CLEANROOM/lwjgl3-stb-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-stb/3.3.4-27-CLEANROOM/lwjgl3-stb-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-tinyfd/3.3.4-27-CLEANROOM/lwjgl3-tinyfd-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-tinyfd/3.3.4-27-CLEANROOM/lwjgl3-tinyfd-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3-tinyfd/3.3.4-27-CLEANROOM/lwjgl3-tinyfd-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3/3.3.4-27-CLEANROOM/lwjgl3-3.3.4-27-CLEANROOM-natives-linux-arm64.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3/3.3.4-27-CLEANROOM/lwjgl3-3.3.4-27-CLEANROOM-natives-linux-arm32.jar
  /home/mattys/.local/share/PollyMC/libraries/org/lwjgl3/lwjgl3/3.3.4-27-CLEANROOM/lwjgl3-3.3.4-27-CLEANROOM-natives-linux.jar
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /home/mattys/.local/share/PollyMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  /home/mattys/.local/share/PollyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/mattys/.local/share/PollyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/mattys/.local/share/PollyMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/mattys/.local/share/PollyMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/mattys/.local/share/PollyMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/mattys/.local/share/PollyMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/mattys/.local/share/PollyMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/mattys/.local/share/PollyMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/mattys/.local/share/PollyMC/libraries/com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /home/mattys/.local/share/PollyMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  /home/mattys/.local/share/PollyMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/mattys/.local/share/PollyMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/commons/commons-compress/1.24.0/commons-compress-1.24.0.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
  /home/mattys/.local/share/PollyMC/libraries/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/mattys/.local/share/PollyMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/libraries/cleanroom-15.24.0.3029-universal.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  /home/mattys/.local/share/PollyMC/libraries/org/ow2/asm/asm-deprecated/7.1/asm-deprecated-7.1.jar
  /home/mattys/.local/share/PollyMC/libraries/com/cleanroommc/bouncepad/0.4.40-cursed/bouncepad-0.4.40-cursed.jar
  /home/mattys/.local/share/PollyMC/libraries/com/ibm/icu/icu4j/74.2/icu4j-74.2.jar
  /home/mattys/.local/share/PollyMC/libraries/org/jline/jline/3.25.0/jline-3.25.0.jar
  /home/mattys/.local/share/PollyMC/libraries/com/typesafe/akka/akka-actor_2.12/2.8.5/akka-actor_2.12-2.8.5.jar
  /home/mattys/.local/share/PollyMC/libraries/com/typesafe/config/1.4.3/config-1.4.3.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/mattys/.local/share/PollyMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/mattys/.local/share/PollyMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/mattys/.local/share/PollyMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/mattys/.local/share/PollyMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/mattys/.local/share/PollyMC/libraries/org/apache/maven/maven-artifact/3.9.5/maven-artifact-3.9.5.jar
  /home/mattys/.local/share/PollyMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  /home/mattys/.local/share/PollyMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  /home/mattys/.local/share/PollyMC/libraries/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar
  /home/mattys/.local/share/PollyMC/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
  /home/mattys/.local/share/PollyMC/libraries/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar
  /home/mattys/.local/share/PollyMC/libraries/jakarta/xml/bind/jakarta.xml.bind-api/4.0.1/jakarta.xml.bind-api-4.0.1.jar
  /home/mattys/.local/share/PollyMC/libraries/jakarta/xml/ws/jakarta.xml.ws-api/4.0.1/jakarta.xml.ws-api-4.0.1.jar
  /home/mattys/.local/share/PollyMC/libraries/jakarta/activation/jakarta.activation-api/2.1.2/jakarta.activation-api-2.1.2.jar
  /home/mattys/.local/share/PollyMC/libraries/org/glassfish/corba/glassfish-corba-omgapi/4.2.5/glassfish-corba-omgapi-4.2.5.jar
  /home/mattys/.local/share/PollyMC/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
  /home/mattys/.local/share/PollyMC/libraries/com/cleanroommc/sponge-mixin/0.16.0+mixin.0.8.5/sponge-mixin-0.16.0+mixin.0.8.5.jar
  /home/mattys/.local/share/PollyMC/libraries/io/github/llamalad7/mixinextras-common/0.3.5/mixinextras-common-0.3.5.jar
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/mattys/.local/share/PollyMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  [✘] +Fugue-1.12.2-0.10.5-beta.jar (disabled)
  [✘] +Fugue-1.12.2-0.10.6-beta.jar (disabled)
  [✘] +Fugue-1.12.2-0.11.0-beta.jar (disabled)
  [✘] +Fugue-1.12.2-0.12.3-beta.jar (disabled)
  [✔] +Fugue-1.12.2-0.14.0-beta
  [✘] +Fugue-1.12.2-0.9.0.jar (disabled)
  [✘] Fugue-1.12.2-0.12.4-beta.jar (disabled)
  [✘] Fugue-1.12.2-0.5.4.jar (disabled)
  [✘] litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar (disabled)
  [✘] malilib-forge-1.12.2-0.10.0-dev.23.nomixin.jar (disabled)

Params:
  --username  --version 1.12.2 --gameDir /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/.minecraft --assetsDir /home/mattys/.local/share/PollyMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+AlwaysActAsServerClassMachine, -XX:+AlwaysPreTouch, -XX:+DisableExplicitGC, -XX:+UseNUMA, -XX:AllocatePrefetchStyle=3, -XX:NmethodSweepActivity=1, -XX:ReservedCodeCacheSize=400M, -XX:NonNMethodCodeHeapSize=12M, -XX:ProfiledCodeHeapSize=194M, -XX:NonProfiledCodeHeapSize=194M, -XX:-DontCompileHugeMethods, -XX:+PerfDisableSharedMem, -XX:+UseFastUnorderedTimeStamps, -XX:+UseCriticalJavaThreadPriority, -XX:+EagerJVMCI, -Dgraal.TuneInlinerExploration=1, -Dgraal.CompilerConfiguration=enterprise, -XX:+UseG1GC, -XX:MaxGCPauseMillis=37, -XX:+PerfDisableSharedMem, -XX:G1HeapRegionSize=16M, -XX:G1NewSizePercent=23, -XX:G1ReservePercent=20, -XX:SurvivorRatio=32, -XX:G1MixedGCCountTarget=3, -XX:G1HeapWastePercent=20, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1RSetUpdatingPauseTimePercent=0, -XX:MaxTenuringThreshold=1, -XX:G1SATBBufferEnqueueingThresholdPercent=30, -XX:G1ConcMarkStepDurationMillis=5.0, -XX:G1ConcRSHotCardLimit=16, -XX:G1ConcRefinementServiceIntervalMillis=150, -XX:GCTimeRatio=99, -XX:+UseTransparentHugePages, -Xlog:gc+init, -Dfile.encoding=UTF-8, -Xms2000m, -Xmx10000m, -Duser.language=en]


[0.002s][info][gc,init] CardTable entry size: 512
[0.086s][info][gc,init] Version: 21.0.2+13-LTS-jvmci-23.1-b30 (release)
[0.086s][info][gc,init] CPUs: 12 total, 12 available
[0.086s][info][gc,init] Memory: 31242M
[0.086s][info][gc,init] Large Page Support: Enabled (Transparent)
[0.086s][info][gc,init] NUMA Support: Disabled
[0.086s][info][gc,init] Compressed Oops: Enabled (Zero based)
[0.086s][info][gc,init] Heap Region Size: 16M
[0.086s][info][gc,init] Heap Min Capacity: 2000M
[0.086s][info][gc,init] Heap Initial Capacity: 2000M
[0.086s][info][gc,init] Heap Max Capacity: 10000M
[0.086s][info][gc,init] Pre-touch: Enabled
[0.086s][info][gc,init] Parallel Workers: 10
[0.086s][info][gc,init] Concurrent Workers: 3
[0.086s][info][gc,init] Concurrent Refinement Workers: 10
[0.086s][info][gc,init] Periodic GC: Disabled
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRSHotCardLimit; support was removed in 21.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option G1ConcRefinementServiceIntervalMillis; support was removed in 20.0
Minecraft process ID: 10895


WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
[18:54:25] [main/INFO] [Bouncepad]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:54:25] [main/INFO] [Bouncepad]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:54:25] [main/INFO] [Bouncepad]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:54:25] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.0 for Minecraft 1.12.2 loading
[18:54:25] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 21.0.2, running on Linux:amd64:6.8.4-zen1-1-zen, installed at /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/Java/graalvm-jdk-21.0.2+13.1
[18:54:25] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[18:54:25] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[18:54:25] [main/WARN] [FML]: The coremod MixinBooter (net.minecraftforge.fml.relauncher.MixinBooterPlugin) is not signed!
[18:54:25] [main/INFO] [FML]: Searching /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/.minecraft/mods for mods
[18:54:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in +Fugue-1.12.2-0.14.0-beta.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:54:25] [main/FATAL] [Bouncepad]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /mnt/5c5de2ef-0d85-40de-9fce-4e4107954c5f/Games/Minecraft/instances/Cleanroom Divine Journey 2 v2/.minecraft for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:118) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:85) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:44) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:134) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:116) [bouncepad-0.4.40-cursed.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:38) [bouncepad-0.4.40-cursed.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: top/outlands/foundation/IExplicitTransformer
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:531) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:454) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:269) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:114) ~[cleanroom-15.24.0.3029-universal.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: top.outlands.foundation.IExplicitTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:230) ~[bouncepad-0.4.40-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:531) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:454) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:269) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:114) ~[cleanroom-15.24.0.3029-universal.jar:?]
	... 8 more
Caused by: java.lang.NullPointerException: Cannot read the array length because "transformedClass" is null
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:219) ~[bouncepad-0.4.40-cursed.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:531) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:454) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:269) ~[cleanroom-15.24.0.3029-universal.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:114) ~[cleanroom-15.24.0.3029-universal.jar:?]
	... 8 more
Process exited with code 1.
```

**Comment by kappa-maintainer** [comment]
0.5.4 is the last stable release for stable (a.k.a. main) branch, so everything is normal
You need the experimental branch of Cleanroom to use newer Fugue
