### ISSUE TITLE
Logisticpipes crash on > 0.14.7

### ISSUE THREAD

**Issue by Toastyice** [CleanroomMC/Fugue#38]
Cleanroom: 0.2.1-alpha
Java: openjdk 21.0.3 2024-04-16 LTS
Logisticpipes: logisticspipes-0.10.4.49.jar
CodeChickenLib-1.12.2-3.2.3.358-universal
using version  0.14.7 works
Full log: https://mclo.gs/7QsF8MS
`
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Logistics Pipes (logisticspipes)
Caused by: java.lang.ClassNotFoundException: logisticspipes.network.packets.pipe.PipePositionPacket
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:258)
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:265)
	at logisticspipes.utils.StaticResolverUtil.lambda$null$0(StaticResolverUtil.java:35)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: logisticspipes.network.packets.pipe
	at java.base/java.lang.ClassLoader.definePackage(Unknown Source)
	at java.base/java.net.URLClassLoader.definePackage(Unknown Source)
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:205)
	... 15 more`

**Comment by kappa-maintainer** [comment]
Please try latest Cleanroom from action

**Comment by Toastyice** [comment]
same issue: https://mclo.gs/Z1J1G2b
used version: [universal-0.2.1-alpha+build.6.run.612](https://github.com/CleanroomMC/Cleanroom/actions/runs/9138328138/artifacts/1515535426)

**Comment by kappa-maintainer** [comment]
You are not updating Cleanroom properly, you need to override the json so the launcher could get the new foundation

**Comment by Toastyice** [comment]
Is there a tutorial on how to do that? 
I've replaced the release cleanroom-0.2.1-alpha-universal.jar with the one from the actions and renamed it.
(Sorry I'm new to this)

**Comment by kappa-maintainer** [comment]
You need to override patches/ folder too

**Comment by Toastyice** [comment]
works with the action build thanks @kappa-maintainer
