### ISSUE TITLE
BDLib crash on 40d0f06

### ISSUE THREAD

**Issue by LinkIsGrim** [CleanroomMC/Fugue#39]
Cleanroom: https://github.com/CleanroomMC/Cleanroom/commit/37ce78cf7c48db6cd88754cbb22cbb1eb6b141a5
Fugue: 40d0f06
BDLib: https://www.curseforge.com/minecraft/mc-mods/bdlib/files/4675629 (also tried https://www.curseforge.com/minecraft/mc-mods/bdlib/files/2518031 and prior 1.12 versions, same crash)
Java: OpenJDK 21.0.3 (Red Hat)

Full log: https://mclo.gs/Bq7aaHG

<details>
<summary>Crash log summary</summary>
java.lang.NoClassDefFoundError: scala/collection/Seq
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:402)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:597)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:303)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:281)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:217)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:599)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:262)
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:269)
	... 40 more
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:233)
	... 41 more
</details>

**Comment by kappa-maintainer** [comment]
Please install scalar
Check Cleanroom repository readme
