### ISSUE TITLE
[HammerLib] Crashes on Startup

### ISSUE THREAD

**Issue by Yuyu-1115** [CleanroomMC/Fugue#62]
### Your CleanroomMC Discord Username

yuyu15._

### Cleanroom Version

0.2.3-alpha build30 run 759

### Java Version

Java 22

### Graphics Card Vendor

Other (Please Specify)

### Bug Report

Device: Apple M3 MacBook Air 16GB/512GB
[Logs](https://mclo.gs/wsodoxa)

I encountered this problem when trying launching DJ2 with Fugue, Scalar, and Forgelin-Continuous installed. However, problem still arises with only HammerLib, Scalar and Fugue installed.
Also, the problem arises with both Java 22 and Java 21.

The Fatal Error:
```
Exception caught from launcher
java.lang.IllegalAccessException: no such method: net.minecraft.client.main.Main.main(String[])void/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:906)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3762)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2660)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:75)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:88)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:104)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:957)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
	... 7 more
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more
Exiting with ERROR
Process exited with code 2.
```

### Mod List

Mods:
--
68 | [✔] Fugue 1.12.2 0.16.4
69 | [✔] HammerLib-1.12.2-2.0.6.32
70 | [✔] Scalar 1.12.2 2.11.1

### MMC Instance Notes

This instance is built using Github Action.
Using installer artifact from commit: ea9fd215009abb2d3ef90b0143af88c183b115a7
Action URL: https://github.com/CleanroomMC/Cleanroom/actions/runs/11647856654

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by kappa-maintainer** [comment]
The patches json gone wrong, please install Cleanroom by importing

**Comment by Yuyu-1115** [comment]
*I'm not sure if I should open a new issue, so I'll keep things in this one for now.

I was using the import to install cleanroom, bur re-installing solve this problem.

However, the game crashed after entering the loading screen
All the specs, Java, Cleanroom, and mods were the same. 


The Error Log this time: [Link](https://mclo.gs/RcO0pAl), and the fatal error was the below message.

```
FATAL ERROR in native method: Thread[#1,Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl3.opengl.GL31C.nglGetActiveUniformName(Native Method)
	at org.lwjgl3.opengl.GL31C.glGetActiveUniformName(GL31C.java:491)
	at org.lwjgl.opengl.GL20.glGetActiveUniform(GL20.java:155)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.collectUniforms(VariableShaderProgram.java:204)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.createProgram(VariableShaderProgram.java:179)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.onReload(VariableShaderProgram.java:223)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram$$Lambda/0x000007ff015c2848.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@22.0.2/ArrayList.java:1597)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.lambda$reload$6(VariableShaderProgram.java:352)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram$$Lambda/0x000007ff015bd8c8.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@22.0.2/Executors.java:572)
	at net.minecraft.client.Minecraft.func_152343_a(Minecraft.java:3135)
	at net.minecraft.client.Minecraft.func_152344_a(Minecraft.java:3157)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.reload(VariableShaderProgram.java:348)
	at com.zeitheron.hammercore.client.utils.gl.shading.VariableShaderProgram.reloadShaders(VariableShaderProgram.java:343)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_VariableShaderProgram_reloadShaders_ResourceManagerReloadEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:92)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.zeitheron.hammercore.proxy.RenderProxy_Client.onResourceManagerReload(RenderProxy_Client.java:874)
	at net.minecraftforge.client.resource.ISelectiveResourceReloadListener.func_110549_a(ISelectiveResourceReloadListener.java:33)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:786)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.lang.invoke.LambdaForm$DMH/0x000007ff01004000.invokeStatic(java.base@22.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x000007ff01288c00.invoke(java.base@22.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@22.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@22.0.2/DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@22.0.2/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@22.0.2/Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(java.base@22.0.2/DirectMethodHandle$Holder)
	at java.lang.invoke.LambdaForm$MH/0x000007ff01118800.invoke(java.base@22.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@22.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@22.0.2/DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@22.0.2/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@22.0.2/Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
	at java.lang.invoke.LambdaForm$DMH/0x000007ff01004400.invokeStaticInit(java.base@22.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x000007ff01004c00.invokeExact_MT(java.base@22.0.2/LambdaForm$MH)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Process crashed with exitcode 6.
```

**Comment by kappa-maintainer** [comment]
Ah, you are on ARM
Try updating Prism to 9.x and use Java 21, if it didn't work try to run the game without any mods

**Comment by Yuyu-1115** [comment]
I'm on Prism 9.1, and switching to Java 21 doesn't solve the issue
Also, running the game without any mods is fine. I can create a new world, run around... etc.

**Comment by Yuyu-1115** [comment]
Just to add some, I believe this is an ARM issues. I did run DJ2 servers on x86 Windows using cleanroom, and things are working as expected, I can connect the server using forge client as well.

**Comment by kappa-maintainer** [comment]
LWJGL on Mac is a known problem, we are still waiting for next lwjgl release

**Comment by Yuyu-1115** [comment]
Ah, I see. Thanks for helping!

**Comment by MCTian-mi** [comment]
should this get re-opened?

**Comment by kappa-maintainer** [comment]
MacOS problem is tracked as a Cleanroom issue, not Fugue
