### ISSUE TITLE
Crash with gravisuite 3.1.1 for 1.12.2

### ISSUE THREAD

**Issue by BassBaritoneHere** [CleanroomMC/Fugue#65]
### Cleanroom Version

Cleanroom_MMC 0.2.3-alpha-build.36.run.771

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Cleanroom Version: 0.2.3-alpha+build.36.run.771
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1815672336 bytes (1731 MB) / 4294967296 bytes (4096 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Cleanroom 0.2.3-alpha+build.36.run.771 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                               | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                        | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                        | None                                     |
	| LCH   | configanytime                     | 3.0               | cleanroom-0.2.3-alpha+build.36.run.771-universal.jar | None                                     |
	| LCH   | cleanroom                         | 0.2.3-alpha       | cleanroom-0.2.3-alpha+build.36.run.771-universal.jar | None                                     |
	| LCH   | FML                               | 8.0.99.99         | cleanroom-0.2.3-alpha+build.36.run.771-universal.jar | None                                     |
	| LCH   | forge                             | 14.23.5.2860      | cleanroom-0.2.3-alpha+build.36.run.771-universal.jar | None                                     |
	| LCH   | creativecoredummy                 | 1.0.0             | minecraft.jar                                        | None                                     |
	| LCH   | mixinbooter                       | 10.1              | cleanroom-0.2.3-alpha+build.36.run.771-universal.jar | None                                     |
	| LCH   | fugue                             | 1.12.2-0.16.4     | +Fugue-1.12.2-0.16.4.jar                             | None                                     |
	| LCH   | ic2                               | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | advanced_solar_panels             | 4.3.0             | Advanced+Solar+Panels-4.3.0.jar                      | None                                     |
	| LCH   | advanced_machines                 | 61.0.1            | AdvancedMachines_1.12.2_61.0.1.jar                   | None                                     |
	| LCH   | creativecore                      | 1.10.0            | creativecore_v1.10.71_mc1.12.2.jar                   | None                                     |
	| LCH   | ambientsounds                     | 3.0               | AmbientSounds_v3.1.7_mc1.12.2.jar                    | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358         | CodeChickenLib_1.12.2_3.2.3.358_universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ptrmodellib                       | 1.0.5             | PTRLib-1.0.5.jar                                     | None                                     |
	| LCH   | props                             | 2.6.3.7           | Decocraft-2.6.3.7_1.12.2.jar                         | None                                     |
	| LCH   | endercore                         | 1.12.2-0.5.78     | EnderCore-1.12.2-0.5.78.jar                          | None                                     |
	| LCH   | jei                               | 4.16.1.1013       | jei_1.12.2-4.16.1.1013.jar                           | None                                     |
	| LCH   | enderio                           | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiointegrationtic             | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiobase                       | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderioconduits                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiointegrationforestry        | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiointegrationticlate         | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderioinvpanel                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiomachines                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | enderiopowertools                 | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                            | None                                     |
	| LCH   | forgelin                          | 1.8.4             | Forgelin-1.8.4.jar                                   | None                                     |
	| LCH   | futuremc                          | 0.2.6             | Future-MC-0.2.20.jar                                 | None                                     |
	| LCE   | gravisuite                        | 3.1.1             | GravitationSuite_1.12.2_3.1.1.jar                    | None                                     |
	| LC    | waila                             | 1.8.26            | Hwyla_1.8.26_B41_1.12.2.jar                          | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844 | ironchest_1.12.2_7.0.72.847.jar                      | None                                     |
	| LC    | journeymap                        | 1.12.2-5.7.1p2    | journeymap-1.12.2-5.7.1p2.jar                        | None                                     |
	| LC    | mousetweaks                       | 3.1.4             | mousetweaks-1.12.2-3.1.4.jar                         | None                                     |
	| LC    | nei                               | 2.4.3             | NotEnoughItems_1.12.2_2.4.3.245_universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | smoothzoom                        | 1.0               | Smooth Zoom-1.0.jar                                  | None                                     |
	| LC    | vintagium                         | 0.1               | vintagium-mc1.12.2-0.1.jar                           | None                                     |
	| LC    | wawla                             | 2.6.275           | Wawla_1.12.2_2.6.275.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
FutureMC (Future-MC-0.2.20.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Sodium (vintagium-mc1.12.2-0.1.jar)
  
MixinBooter (cleanroom-0.2.3-alpha+build.36.run.771-universal.jar)
  
Fugue (+Fugue-1.12.2-0.16.4.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CreativePatchingLoader (creativecore_v1.10.71_mc1.12.2.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 561.09' Renderer: 'NVIDIA GeForce RTX 4090/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/makarov/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[00:41:27] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\makarov\Downloads\MultiMC\instances\Cleanroom_MMC 0.2.3-alpha-build.36.run.771\.minecraft\crash-reports\crash-2024-11-15_00.41.27-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Mod List

  [✔️] !mixinbooter-10.0.jar
  [✔️] +Fugue-1.12.2-0.16.4.jar
  [✔️] Advanced+Solar+Panels-4.3.0.jar
  [✔️] AdvancedMachines_1.12.2_61.0.1.jar
  [✔️] AmbientSounds_v3.1.7_mc1.12.2.jar
  [✔️] CodeChickenLib_1.12.2_3.2.3.358_universal.jar
  [✔️] creativecore_v1.10.71_mc1.12.2.jar
  [✔️] Decocraft-2.6.3.7_1.12.2.jar
  [✔️] EnderCore-1.12.2-0.5.78.jar
  [✔️] EnderIO-1.12.2-5.3.72.jar
  [✔️] Forgelin-1.8.4.jar
  [✔️] Future-MC-0.2.20.jar
  [✔️] GravitationSuite_1.12.2_3.1.1.jar
  [✔️] Hwyla_1.8.26_B41_1.12.2.jar
  [✔️] industrialcraft-2-2.8.170-ex112.jar
  [✔️] ironchest_1.12.2_7.0.72.847.jar
  [✔️] jei_1.12.2-4.16.1.1013.jar
  [✔️] journeymap-1.12.2-5.7.1p2.jar
  [📁] memory_repo (folder)
  [✔️] mousetweaks-1.12.2-3.1.4.jar
  [✔️] NotEnoughItems_1.12.2_2.4.3.245_universal.jar
  [✔️] PTRLib-1.0.5.jar
  [✔️] Smooth Zoom-1.0.jar
  [✔️] vintagium-mc1.12.2-0.1.jar
  [✔️] Wawla_1.12.2_2.6.275.jar

### MMC Instance Notes

Sorry, i dont know where

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I have installed [Fugue](https://github.com/CleanroomMC/Fugue) and it does not fix this issue.
- [X] I have installed [Scalar 2.11.1](https://github.com/CleanroomMC/Scalar/releases/tag/2.11.1) and it does not fix this issue.
- [X] I am running a test build from Cleanroom Github Actions.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by BassBaritoneHere** [comment]
Seems easy, fields modifiers??

Time: 2024-11-15 01:02
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gravitation Suite (gravisuite)
Caused by: java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: ic2.core.util.Keyboard$Key.keys/[Lic2.core.util.Keyboard$Key;/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:207)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:144)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1200)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1169)
	at java.base/java.lang.reflect.Field.get(Field.java:444)
	at ic2.core.util.ReflectionUtil.setValue(ReflectionUtil.java:115)
	at com.chocohead.gravisuite.GraviKeys$GraviKey.addKey(GraviKeys.java:54)
	at com.chocohead.gravisuite.GraviKeys$GraviKey.<init>(GraviKeys.java:46)
	at com.chocohead.gravisuite.GraviKeys$GraviKey.<clinit>(GraviKeys.java:27)
	at com.chocohead.gravisuite.GraviKeys.<clinit>(GraviKeys.java:80)
	at com.chocohead.gravisuite.Gravisuite.load(Gravisuite.java:65)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:303)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:281)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:217)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:634)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalAccessException: static final field has no write access: ic2.core.util.Keyboard$Key.keys/[Lic2.core.util.Keyboard$Key;/putStatic, from class java.lang.Object (module java.base)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:889)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3609)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3600)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1619)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:185)
	... 51 more

**Comment by BassBaritoneHere** [comment]
SORRY! I tried using build from releases (0.2.3-alpha) instead of actions buils of cleanroom and it worked. Im sorry
